---
homeassistant:
  name: WOPR
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
http:
updater:
recorder:
history:
logbook:

#
ios:
wake_on_lan:
sun:
emulated_hue:
  expose_by_default: false


sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml

media_player: !include media_players.yaml
camera: !include cameras.yaml

zone: !include zones.yaml

notify: !include notify.yaml

automation: !include_dir_merge_list automation/
