---
- platform: tplink
  host: !secret switch_lamp
  name: Living room lamp

- platform: transmission
  host: !secret switch_transmission_host
  username: !secret switch_transmission_user
  password: !secret switch_transmission_pass

- platform: command_line
  switches:
    motion_record:
      command_on: 'systemctl start motion'
      command_off: 'systemctl stop motion'
      command_state: 'systemctl status motion | grep "Active: active"'
      friendly_name: Living room camera
    presence:
      command_on: 'touch /tmp/presence.lock'
      command_off: 'rm /tmp/presence.lock'
      command_state: 'ls /tmp/presence.lock'
