- alias: Motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.presence
      state: 'off'
  action:
    service: notify.wopr
    data_template:
      title: "Motion detected!"
      message: "Motion detected!"
      target: "device/mm"

